# -*- coding: utf-8 -*-
"""CO421-Bowling-cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8g8Swd47JFD5AG3uvN32YiCKqPYXjkt
"""

from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

wb = gc.open_by_url('https://docs.google.com/spreadsheets/d/1peLpNFoEu8NHtVPttJXz4-aScixYu5dh_-6gYPOi9rQ/edit?ts=5f7f50be#gid=924430584')

sheet = wb.worksheet('bo_data')

data = sheet.get_all_values()

df = pd.DataFrame(data)
df.columns = df.iloc[0]
df = df.iloc[1:]

df.head()

del df["u"]
del df["v"]
del df["w"]
del df["Bowler Score"]
del df["BBI"]
del df["BBI-copy-1"]
del df["BBI-copy-2"]
del df["Span"]

df.dtypes

df.__eq__('').sum()

df.__eq__('-').sum()

df.replace('',"?",inplace = True)
df.replace('-',"?",inplace = True)

df.__eq__('?').sum()

df.replace('?',np.nan,inplace = True)

df.__eq__('?').sum()

df["Height (cm)"]= df["Height (cm)"].astype(float)

print(df.info())

print(df['Height (cm)'].unique())

print(df['Bowling Style'].unique())

from statistics import mean
df["Height (cm)"].fillna(df["Height (cm)"].mean(),inplace = True)

df.head()

import statistics
from statistics import mode
print(statistics.mode(df['Bowling Style']))

df['Bowling Style'].fillna('Right-arm fast-medium',inplace=True)

print(df.isnull().sum())

from google.colab import files
df.to_csv('421_bowling_missingValues.csv' , index=False)
files.download('421_bowling_missingValues.csv')

df["Bowling Style"]= df["Bowling Style"].astype('category')
df["Bowling Style"]= df["Bowling Style"].cat.codes

df["Mat"]= df["Mat"].astype(int)
df["Inns"]= df["Inns"].astype(int)
df["Balls"]= df["Balls"].astype(int)
df["Runs"]= df["Runs"].astype(int)
df["Wkts"]= df["Wkts"].astype(int)
df["BBI-calc"]= df["BBI-calc"].astype(float)
df["SR"]= df["SR"].astype(float)
df["Ave"]= df["Ave"].astype(float)
df["Econ"]= df["Econ"].astype(float)
df["4"]= df["4"].astype(int)
df["Man of the match"]= df["Man of the match"].astype(int)
df["5"]= df["5"].astype(int)
df["Hat tricks"]= df["Hat tricks"].astype(int)

print(df.info())

from pandas.plotting import scatter_matrix
sm = scatter_matrix(df, alpha=0.2, figsize=(12, 12), diagonal='kde')

#Change label rotation
[s.xaxis.label.set_rotation(90) for s in sm.reshape(-1)]
[s.yaxis.label.set_rotation(0) for s in sm.reshape(-1)]

#May need to offset label when rotating to prevent overlap of figure
[s.get_yaxis().set_label_coords(-1.5,0.5) for s in sm.reshape(-1)]

#Hide all ticks
[s.set_xticks(()) for s in sm.reshape(-1)]
[s.set_yticks(()) for s in sm.reshape(-1)]
plt.show()