# -*- coding: utf-8 -*-
"""CO421-FYP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baBnmY0wXlBUoUsLa_g1j66Ih6j-Xs1-
"""

from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

wb = gc.open_by_url('https://docs.google.com/spreadsheets/d/1peLpNFoEu8NHtVPttJXz4-aScixYu5dh_-6gYPOi9rQ/edit#gid=670066504')

sheet = wb.worksheet('bt_data')

data = sheet.get_all_values()

df = pd.DataFrame(data)
df.columns = df.iloc[0]
df = df.iloc[1:]

df.head()

print ("Dataset Length: ", len(df))
print ("Dataset Shape: ", df.shape)

type(df.iloc[2][4])

print(df.info())

print(df.__eq__('-').sum())

df.__eq__('-').sum()

df.__eq__('').sum()

#df["Height (cm)"]= df["Height (cm)"].astype(int)

df.replace('',"?",inplace = True)
df.replace('-',"?",inplace = True)

df.replace('?',np.nan,inplace = True)

df.__eq__('?').sum()

print(df['Height (cm)'].unique())

df["Height (cm)"]= df["Height (cm)"].astype(float)

df.dtypes

df["Mat"]= df["Mat"].astype(float)
df["Inns"]= df["Inns"].astype(float)
df["NO"]= df["NO"].astype(float)
df["HS_NO"]= df["HS_NO"].astype(float)
df["Ave"]= df["Ave"].astype(float)
df["BF"]= df["BF"].astype(float)
df["SR"]= df["SR"].astype(float)
df["100"]= df["100"].astype(float)
df["50"]= df["50"].astype(float)
df["0"]= df["0"].astype(float)
df["Last 4 match runs mean"]= df["Last 4 match runs mean"].astype(float)
df["Man of the match"]= df["Man of the match"].astype(float)
df["Runs"]= df["Runs"].astype(float)
df["HS"]= df["HS"].astype(float)

df.dtypes

df["Man of the match"].replace(np.nan,0, inplace=True)

df.mean()

df["Ave"].replace(np.nan,18.805680, inplace=True)
df["Height (cm)"].replace(np.nan,181.430074, inplace=True)
df["SR"].replace(np.nan,65.630124, inplace=True)
df["Last 4 match runs mean"].replace(np.nan,13.253897, inplace=True)

print(df.isnull().sum())

print(df["Batting Style"].value_counts())

df["Batting Style"].replace(np.nan,'R', inplace=True)

#df.to_csv("E:/University Works/4th Year/Semester 7/CO421 - Final Year Project/bt-copy.csv",sep=',')

from google.colab import files
df.to_csv('421_proj_missingValues.csv' , index=False)
files.download('421_proj_missingValues.csv')